version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
commands:
  restore_node_modules:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-master
      - restore_cache:
          name: Restore node_modules dependencies
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
  save_node_modules:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules dependencies
          paths:
            - node_modules
            - packages/context/node_modules
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
jobs:
  install_node_modules:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - run: yarn install --frozen-lockfile
      - save_node_modules
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - run: yarn run test
workflows:
  build:
    jobs:
      - install_node_modules
      - test:
          requires:
            - install_node_modules
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - install_node_modules
      - test:
          requires:
            - install_node_modules
